---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
stringData:
  config.yaml: |-
    cluster_scope: {{ if .Values.cluster_scope }}true{{ else }}false{{ end }}
    watched_namespaces: {{ if .Values.watched_namespaces }}{{ toJson .Values.watched_namespaces }}{{ else }}[]{{ end }}
    skopeo:
      image: "{{ .Values.skopeo.image.repository }}:{{ .Values.skopeo.image.tag }}"
      image_pull_policy: "{{ .Values.skopeo.image.pullPolicy }}"
{{ if .Values.skopeo.ca_trust_bundle }}
      ca_trust_bundle: |
{{ .Values.skopeo.ca_trust_bundle | indent 8 }}
  {{ end }}
