FROM docker.io/library/rust:1 AS debug

WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir -p src && echo "" > src/main.rs && echo "" > src/crdgen.rs && cargo build --target x86_64-unknown-linux-gnu || true
COPY src src
RUN cargo build --target x86_64-unknown-linux-gnu
CMD ["/app/target/x86_64-unknown-linux-gnu/debug/image-sync-operator"]
