FROM docker.io/library/rust:1 AS debug

WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir -p src && echo 'fn main() { println!("hello world")}' > src/main.rs &&\
    RUSTFLAGS="-D warnings -D nonstandard-style -D let-underscore" cargo build
RUN rustup component add clippy &&\
    cargo clippy -- --no-deps -D warnings -D nonstandard-style -D let-underscore
COPY src src
RUN cargo clippy -- --no-deps -D warnings -D nonstandard-style -D let-underscore &&\
    RUSTFLAGS="-D warnings -D nonstandard-style -D let-underscore" cargo build &&\
    cp target/debug/image-sync-operator /image-sync-operator
CMD ["/image-sync-operator"]
