# rust @ 1.97-slim
FROM docker.io/library/rust@sha256:5c6f46a6e4472ab1ca7ba7d494e6677f2f219ebc02f32025d3986f057635ec9c AS build

WORKDIR /app
COPY Cargo.toml Cargo.lock ./
# Run the build against a fake main.rs to pack all dependencies. This makes incremental builds much faster
RUN mkdir -p src && echo 'fn main() { println!("hello world")}' > src/main.rs &&\
    CARGO_BUILD_WARNINGS=deny cargo build

# Copy the real source code and build
COPY src src
RUN CARGO_BUILD_WARNINGS=deny cargo build &&\
    cp target/debug/image-sync-operator /image-sync-operator

# To keep the debug image from being huge, we copy the binary into a slim debian image from tag 12-slim
FROM docker.io/library/debian@sha256:7b140f374b289a7c2befc338f42ebe6441b7ea838a042bbd5acbfca6ec875818 AS debug
COPY --from=build /image-sync-operator /image-sync-operator
USER 9999:9999
CMD ["/image-sync-operator"]
